### ISSUE TITLE
Research new System Architecture

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-package-python#2]
## Task Description
Understand the current system's technology stack, code + deployment structure and the issues it suffers from. Research and document a new system architecture design that will provide a minimal and clean solution free from the current issues.

## Acceptance Criteria
- [x] Diagram old and new system architecture.
- [x] Document consolidated technology stack for frontend.
- [x] Setup Python (pip installable) and Javascript (npm installable) packages for reusable code.
- [x] Create template repository exemplifying how our micro-services should be structured.

**Comment by SKairinos** [comment]
[Frontend service template](https://github.com/ocadotechnology/codeforlife-service-template).
[Frontend coding conventions](https://github.com/ocadotechnology/codeforlife-service-template/blob/main/docs/frontend/CODING-CONVENTION.md)
[Front end tech stack](https://github.com/ocadotechnology/codeforlife-service-template/blob/main/docs/frontend/TECH-STACK.md)
[Frontend package](https://github.com/ocadotechnology/codeforlife-package-javascript)
[Old and new system architecture diagram](https://miro.com/app/board/uXjVPhu7IYw=/?share_link_id=518623291955)

**Comment by SKairinos** [comment]
Regarding the frontend testing framework, here are the key considerations:

See [Cypress vs Selenium](https://www.browserstack.com/guide/cypress-vs-selenium).

Pros of using Cypress over Selenium:
1. Tests are easier to write. Cypress supports: auto-waiting for assertions, simple load/retry logic, intuitive spies/stubs, timers, [component-level testing](https://docs.cypress.io/guides/component-testing/react/quickstart#Running-the-Test), etc. 
2. Captures snapshots of the execution, allowing devs to "time-travel" and see where things went wrong.
3. Ensures components are in view (via auto-scrolling) before testing.
4. Supports hot-reloading, executing as you type.
5. Auto-generates test results.

Cons of using Cypress over Selenium:
1. Doesn't support testing on Safari (due to Apple's EULA).
2. Doesn't support launching multiple browsers at the same time.
3.  Doesn't support multi-tabs.
4. Tests can only be written in JS.
5. Limited support for iFrames.

Mitigating Cypress' cons (Browserstack to the rescue!!!):
1. [Run Cypress Tests in Parallel](https://www.browserstack.com/docs/automate/cypress/run-tests-in-parallel)
2. Cypress [Safari testing](https://www.browserstack.com/guide/cypress-safari-testing).
