### ISSUE TITLE
Investigate Common / circular dependencies - project structure

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-package-python#3]
https://docs.djangoproject.com/en/4.1/intro/reusable-apps/

## Task Description
We need to investigate and figure out if the circular dependencies that have been identified most recently will still be an issue or not once we've moved all the code to the new project.

This is only an investigation task not a task to clean up the circular dependencies.

## Acceptance Criteria
- [ ] Use the link above as starting information
- [ ] If the circular dependencies are still an issue, compare them with the circular dependencies doc and add any missing ones.
- [ ] If they are no longer an issue, consider whether `cfl-common` can be deleted and discuss the steps for it (new task)

### Analytics Requirements
None

### Copywrite Requirements
None

**Comment by faucomte97** [comment]
https://docs.google.com/document/d/1WLJIG3ZHcD5T43K5hrJd88Vbbrm0LQ9hvTskV3YA_Us/edit#
